name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        working-directory: ./packages/react-swing-server
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./packages/react-swing-server
        run: ./gradlew build

      - name: Upload artifact
        working-directory: ./packages/react-swing-server
      - uses: actions/upload-artifact@v2
        with:
          name: react-swing-server.jar
          path: ./build/libs/react-swing-server.jar
