name: Publish react-swing to Github Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm ci && npm publish
        working-directory: packages/react-swing
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
